#!/usr/bin/env python
import unittest
from attributes.WireSymmetryAttributeTest import WireSymmetryAttributeTest
from attributes.WireSymmetryVertexOrbitAttributeTest import WireSymmetryVertexOrbitAttributeTest
from attributes.WireSymmetryEdgeOrbitAttributeTest import WireSymmetryEdgeOrbitAttributeTest
from core.WireNetworkTest import WireNetworkTest
from inflator.ParameterHandlerTest import ParameterHandlerTest
from inflator.ParameterHandler2DTest import ParameterHandler2DTest
from inflator.WireInflatorTest import WireInflatorTest
from inflator.WireInflator2DTest import WireInflator2DTest
from inflator.WireTilerTest import WireTilerTest
from parameter.PatternParameterTest import PatternParameterTest
from parameter.ThicknessParameterTest import ThicknessParameterTest
from parameter.VertexThicknessParameterTest import VertexThicknessParameterTest
from parameter.EdgeThicknessParameterTest import EdgeThicknessParameterTest
from parameter.VertexOffsetParameterTest import VertexOffsetParameterTest
from parameter.ParameterFactoryTest import ParameterFactoryTest
from utils.TriangulationTest import TriangulationTest

if __name__ == "__main__":
    unittest.main();
