###-----PBS Directives Start-----###

#PBS -V
#PBS -S /bin/bash
#PBS -N gv_d1_direct
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:30:00
#PBS -l mem=8GB
#PBS -M fjp234@nyu.edu
#PBS -m a
#PBS -e localhost:\${PBS_O_WORKDIR}/\${PBS_JOBNAME}.e\${PBS_JOBID}
#PBS -o localhost:\${PBS_O_WORKDIR}/\${PBS_JOBNAME}.o\${PBS_JOBID}
#PBS -t 0-8

###-----PBS Directives End-----###
PATOPT=$HOME/microstructures/pattern_optimization
WCOPT=$HOME/microstructures/worst_case_stress
resultdir=$SCRATCH/gradient_validation/wc_stress/direct_nsv/d1/
mkdir -p $resultdir
cd $resultdir
$WCOPT/GradientComponentValidation -n -p $MICRO_DIR/patterns/3D/reference_wires/pattern0746.wire -m $MICRO_DIR/materials/B9Creator.material -d1 -l0.03 -u0.10 $PATOPT/default_job_isoinflator.opt ${PBS_ARRAYID} 40 -IV > p${PBS_ARRAYID}.txt
